version: 2
updates:
 
  # Maintain dependencies for poetry
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
    commit-message:
        prefix: "â¬†ï¸ ğŸ¤– Dependencies"


  # Maintain dependencies for GitHub Actions
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   #target-branch: "dev"
  #   schedule:
  #     interval: "weekly"
  #   commit-message:
  #     prefix: "â¬†ï¸ Dep"

  # Maintain dependencies for pip
  #- package-ecosystem: "pip"
  #  directory: "/.requirements/"
  #  schedule:
  #    interval: "weekly"
  #  commit-message:
  #    prefix: "â¬†ï¸ Dep"
