########################################
###          EXAMPLE SETTINGS        ###
#######################################


# DISCORD BOT on ethereum chain using 
# uniswap v2 router

# bot_token = '1212121212121'
# bot_channel_id = '121212121212'
# apprise_url = 'discord://1212121212121/121212121212'
# dex_wallet_address = '0x1234567890123456789012345678901234567890'
# dex_private_key = '0xdeadbeef'
# dex_block_explorer_api = '42342342342'

# TELEGRAM BOT on CEX Binance
    # bot_token = '1212121212121'
    # bot_channel_id = '-112121212121'
    # bot_api_id = '1212121212912'
    # bot_api_hash = '121212121212121' 
    # apprise_url = 'tgram://1212121212121/-112121212121'
    # cex_name = 'binance' 
    # cex_api = 'abcabcabcabcabcabc' 
    # cex_secret = 'abcabcabcabcabcabc' 

#DISCORD BOT on BSC chain using pancakeswap v2 router and custom plugin setup
    # bot_token = '1212121212121'
    # bot_channel_id = '121212121212'
    # apprise_url = 'discord://1212121212121/121212121212'
    # dex_wallet_address = '0x1234567890123456789012345678901234567890'
    # dex_private_key = '0xdeadbeef'
    # dex_router_contract_addr = "0x10ED43C718714eb63d5aA57B78B54704E256024E"
    # dex_factory_contract_addr = "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73"
    # dex_block_explorer_url = 'https://api.bscscan.com/api'
    # dex_block_explorer_api = '42342342342'
    # trading_asset_address = "0xe9e7cea3dedca5984780bafc599bd69add087d56"
    # action_identifier = "PUMP DUMP"
    # mapping = [
    #     { id = "ETH", alt = "WETH" },
    # ]
    # live_tv_url ='https://reuters-reutersnow-1.plex.wurl.com/manifest/playlist.m3u8'

#MATRIX BOT on Polygon chain using zerox protocol
    # bot_token = '1212121212121'
    # bot_channel_id = '121212121212'
    # bot_hostname='matrix.org'
    # bot_user='itsme'
    # bot_pass='mario'
    # apprise_url = 'discord://1212121212121/121212121212'
    # dex_wallet_address = '0x1234567890123456789012345678901234567890'
    # dex_private_key = '0xdeadbeef'
    # dex_protocol_type = "0x"
    # dex_rpc = "https://rpc.ankr.com/polygon"
    # dex_0x_url = "https://polygon.api.0x.org/"
    # dex_router_contract_addr = "0xdef1c0ded9bec7f1a1670819833240f027b25eff"
    # dex_block_explorer_url = 'https://api.polygonscan.com/api'
    # dex_block_explorer_api = '42342342342'
    # trading_asset_address = "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
