[default]
loglevel = "INFO"
host = "0.0.0.0"
port = 8080
ping = "8.8.8.8"
webhook_secret = "123abc"
bot_prefix = "/"
bot_command_help = "help"
bot_command_bal = "bal"
bot_command_quote = "q"
bot_command_pos = "pos"
bot_command_trading = "trading"
bot_command_news = "live"
bot_command_restart = "restart"
bot_ignore = "ğŸ—¿ âš ï¸ ğŸ“Š ğŸ¦ â¬‡ï¸ â¬†ï¸"
bot_msg_help = "ğŸ¦ <code>/bal</code> ğŸ“¦ <code>buy BTCUSDT</code> ğŸ”€ <code>/trading</code>"

# CEX config
cex_name = ""
cex_api = ""
cex_secret = ""
cex_password = ""
cex_testmode = true
cex_defaulttype = "SPOT"
cex_ordertype = "MARKET"

# TRADING
trading_enabled = true #bool
trading_asset = "USDT"
trading_risk_amount = 10
trading_stop_loss = 1000
trading_take_profit = 1000
