[default]
loglevel = "INFO"
host = "0.0.0.0"
port = 8080
ping = "8.8.8.8"
bot_prefix = "/"
bot_command_help = "help"
bot_command_bal = "bal"
bot_command_pos = "pos"
bot_command_trading = "trading"
bot_command_restart = "restart"
bot_command_quote = "q"
bot_ignore = "ğŸ—¿ âš ï¸ ğŸ“Š ğŸ¦ â¬‡ï¸ â¬†ï¸"
bot_msg_help = "ğŸ¦ <code>/bal</code> ğŸ“¦ <code>buy BTCUSDT</code> ğŸ”€ <code>/trading</code>"

# --------------------------

bot_token = ""
bot_channel_id = ""

telethon_api_id = ""
telethon_api_hash = ""

matrix_hostname = ""
matrix_user = ""
matrix_pass = ""

discord_webhook_id = ""
discord_webhook_token = ""

# CEX config for CeFi
cex_name = ""
cex_api = ""
cex_secret = ""
cex_password = ""
cex_testmode = ""
cex_defaulttype = "SPOT"
cex_ordertype = "MARKET"

#MT/IB config for CeFi
# cex_host = ""
# cex_account = ""

#DXSP config for DEFI
dex_chain_id = 1
dex_wallet_address = ""
dex_private_key = ""
dex_trading_slippage = 2

# TRADING
trading_quote_ccy = "USDT"
trading_risk_amount = 10
trading_stop_loss = 1000
trading_take_profit = 1000
