name: ğŸš€ Deploy


on:
  workflow_run:
    workflows: ["ğŸ¥·ğŸ³ Nightly Docker"]
    branches: [ "dev" ]
    types: 
      - completed

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          
if: ${{ github.event.workflow_run.conclusion == 'success' }}
jobs:
  deploy:
    name: ğŸš€ Deploy staging 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only