name: ğŸ³Docker

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["ğŸ‘·Flow"]
  #   types: [completed]
  #   branches: ["main"]
  release:
      types: [published]

jobs:
  docker:
    uses: mraniki/coding_toolset/.github/workflows/ğŸ³Docker.yml@main
    secrets: inherit
