name: âœ¨Flow

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '42 23 * * 5'

jobs:
  lint:
    uses: mraniki/coding_toolset/.github/workflows/ğŸ¦ºLint.yml@main
  # test:
  #   needs: [lint]
  #   uses: mraniki/coding_toolset/.github/workflows/ğŸ§ªTest.yml@main
  security:
    needs: [lint]
    uses: mraniki/coding_toolset/.github/workflows/ğŸ”Security.yml@main
  # build:
  #   needs: [lint]
  #   uses: mraniki/coding_toolset/.github/workflows/ğŸBuild.yml@main
  version:
    needs: [lint]
    uses: mraniki/coding_toolset/.github/workflows/ğŸ”–Version.yml@main
  # release:
  #   needs: [lint]
  #   uses: mraniki/coding_toolset/.github/workflows/ğŸ“¦Release.yml@main
  docker:
    needs: [lint]
    uses: mraniki/coding_toolset/.github/workflows/ğŸ³Docker.yml@main
    secrets: inherit
  # deploy:
  #   needs: [docker]
  #   uses: mraniki/coding_toolset/.github/workflows/â˜ï¸Deploy.yml@main